name: test-inputs
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: dev
      OS:
        description: "Select OS"
        required: true
        default: ubuntu-latest
jobs:
  test-input:
    runs-on: ${{ inputs.OS }}
    steps:
      - name: deploy the application
        run: echo " deploying app into ${{ inputs.environment}}"
