name: ci/cd
on: 
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome message
        run: echo "welcome ${{ vars.TESTING }}"
  test:
    runs-on: ubuntu-latest
    needs: 
      build
    steps:
      - name: print step1 completed
        run: echo " completed ${{ secrets.TEST-1 }}"
  deploy:
    runs-on: ubuntu-latest
    needs: 
      test
    steps:
      - name: print step2 complted
        run: echo "completed"
