name: test
on:
  workflow_dispatch:
  inputs:
    environments:
     description: "select environments" 
     required: true
     default: dev
    OS:
     description: "select os"
      required: true
      default: ubuntu_latest 
  jobs:
    test:
      runs-on: ${{ inputs.OS }}
      steps:
        -name: deploy to env
        run: echo "print ${{ inputs.environments }}
    

